version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"  # FastAPI backend
      - "8501:8501"  # Streamlit frontend
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/pine_time
      - BACKEND_CORS_ORIGINS=["http://localhost:8501", "http://localhost:8000"]
      - SECRET_KEY=your_secret_key_here_please_change_in_production
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    volumes:
      - .:/app
    restart: always

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pine_time
    ports:
      - "5432:5432"
    restart: always

volumes:
  postgres_data:
