[build]
  command = "pip install -r requirements.txt && pip install -r admin_dashboard/requirements.txt && mkdir -p .streamlit"
  publish = "admin_dashboard"

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/api/*"
  to = "https://pine-time-api.herokuapp.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/user_app.py"
  status = 200
