name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1  # Change to your region
    
    - name: Create Deployment Package
      run: |
        mkdir deployment-package
        cp -r app/ deployment-package/
        cp -r .ebextensions/ deployment-package/
        cp Procfile deployment-package/
        cp requirements.txt deployment-package/
        cd deployment-package
        zip -r ../deploy.zip .
    
    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v21
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: pine-time
        environment_name: Pine-time-env
        version_label: ${{ github.sha }}
        region: us-east-1  # Change to your region
        deployment_package: deploy.zip
        wait_for_environment_recovery: 300